services:

  app:
    container_name: 'social-network-app'
    build: .
    networks:
      - social-network
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: 'social_network_mysql_db'
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    networks:
      -  social-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ANAkonda92
      MYSQL_DATABASE: portal-spolecznosciowy
      MYSQL_PASSWORD: ANAkonda92

networks:
  social-network: